server:
  port: 9090
spring:
  application:
    name: ONLINE-SHOPPING-DEV
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://${DB_SERVICE:localhost:3306}/oshopdb
    username: oshop_user
    password: oshoppwd
    driver-class-name: com.mysql.cj.jdbc.Driver
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://${DISCOVERY_SERVER:localhost}:8761/eureka/
management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include:
        - '*' 
logging:
  pattern: 
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'